name: "Copybara Action"
description: "Transforms and moves code between repositories."
author: "Will Molloy <willjoemolloy@gmail.com> & Ji Paik <jjeonie@gmail.com>"

inputs:
  git_name:
    description: "git config username, for authoring with Copybara"
    required: true
  git_email:
    description: "git config email, for authoring with Copybara"
    required: true
  ssh_key:
    description: "ssh public key, for authenticating with Copybara"
    required: true
  ssh_known_hosts:
    description: "ssh known hosts file contents, for authenticating with Copybara"
    required: true
  path:
    description: "copy.bara.sky file path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - run: |
        mkdir ~/.ssh
        echo $'${{ inputs.ssh_key }}' > ~/.ssh/id_rsa
        echo $'${{ inputs.ssh_known_hosts }}' > ~/.ssh/known_hosts
      shell: bash

    - run: |
        git config --global user.name ${{ inputs.git_name }}
        git config --global user.email ${{ inputs.git_email }}
      shell: bash

    - run: docker pull sharelatex/copybara:latest
      shell: bash

    - run: docker run -v ~/.ssh:/root/.ssh -v ~/.gitconfig:/root/.gitconfig -v "$(pwd)":/usr/src/app -i sharelatex/copybara copybara ${{ inputs.path }}
      shell: bash

branding:
  icon: 'copy'
  color: 'blue'
